Feature/sticky note animation
HackAtUCI/zothacks-site-2023 pull request #114
Opened 2023-11-02 13:56 UTC by tyleryy

### Overview

Animation for resource sticky notes to fly in from the 4th wall (your face/screen) onto the page. The animation is triggered when the user scrolls down and the sticky note is in view.

### Details

Created a "slam in" animation variant that animates scale and opacity to achieve the effect. Converted the Resource Card component elements to motion elements to get the animation to "stagger" for each part of the sticky note.

### Addendum
Open to discussion on the timing and fine-grained details of the animation.

2023-11-02 14:08 UTC, tyleryy commented
This PR can also be used for the mentor apply sticky notes.

2023-11-03 01:11 UTC, tyleryy commented
I can also put the animation on the note cards and the stagger animation will be on the card and text.

2023-11-03 17:19 UTC, samderanova requested changes
This is awesome! Thank you for working on this. A few things I'd like to point out:

2023-11-03 17:19 UTC, samderanova commented on apps/site/src/views/Resources/components/ResourceCard/ResourceCard.module.scss
>  	width: 238px;
Issue: Slightly unrelated, but the width of the card has been hardcoded to a certain value (`344px`), which on the smallest mobile view, causes the sides of all cards to be cut off.

2023-11-03 17:19 UTC, samderanova commented on apps/site/src/views/Resources/components/ResourceCard/ResourceCard.module.scss
>  	width: 238px;
I think we could just reduce the width to 300px

2023-11-03 18:42 UTC, tyleryy commented on apps/site/src/app/(home)/sections/Landing/ApplyButton.tsx
> +} from "@/components/Sticker/Stickers";
shoot I think I branched incorrectly, I will fix that rn

2023-11-04 13:21 UTC, samderanova approved these changes
Great work on the animations!

2023-11-04 15:59 UTC, merged