Feature mentor apply link
HackAtUCI/zothacks-site-2023 pull request #39
Opened 2023-10-03 08:02 UTC by tyleryy

### Overview

Added link to mentor application google form.

Reference [here](https://forms.gle/fwWJtsQ3GXQFGjS47)

2023-10-03 19:38 UTC, tyleryy commented
I also added a `/mentor` redirect route to the form. Let me know if this is desired behavior.

2023-10-03 19:42 UTC, tyleryy commented
Actually, on the redirect, I noticed the web page renders empty first then redirects to the google form.

2023-10-03 20:18 UTC, tyleryy commented
Blocked by apply link PR, will pull to get redirect urls once merged

2023-10-04 16:22 UTC, samderanova requested changes
One small issue and we're good to go! Thanks for working on this as well.

2023-10-04 17:21 UTC, tyleryy commented on apps/site/src/app/mentor/page.tsx
> +import { redirect } from "next/navigation";
yea it was blocked by the other PR. Now that it is merged Ill make the change now! :)

2023-10-04 17:27 UTC, tyleryy commented on apps/site/src/app/mentor/page.tsx
> +import { redirect } from "next/navigation";
kk changes made

2023-10-04 18:19 UTC, tyleryy commented
Ready for Review!

2023-10-04 18:54 UTC, alexanderl19 approved these changes

2023-10-04 18:54 UTC, merged

2023-10-04 19:40 UTC, taesungh commented
Force unmerged given messiness of tree, reopening as #43.